first_name ='sahil'
last_name='ali
full_name=first_name+last_name
country= 'india'
city='greater noida '
age=22
year=2024
is_married=False
is_true=True
is_light_on= False
my_name,ur_name,my_coll,ur_coll='ali','aly','gniot','glb'